version: "3.4"

services:

  postgres:
    container_name: coding-assessment-nodejs_postgres
    image: postgres:15-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      LANG: fr_FR
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=fr-FR"

  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"

  backend:
    container_name: coding-assessment-nodejs
    image: coding-assessment-nodejs
    build:
      context: .
      target: app_node
    volumes:
      - ./:/srv/app
    ports:
      - "9229:9229"
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_NAME: database
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      SQL_ALTER: "true"
      SECRET: devSecret
      MAPBOX_TOKEN: MAPBOX_TOKEN
      OPEN_WEATHER_API_TOKEN: WEATHER_TOKEN
    command: "npm run start:debug"
